# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('academyId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('brief', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activityId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('userId', models.CharField(max_length=60)),
                ('tel', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroomId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('maximum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('collegeId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=60)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Classroom')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.College')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('majorId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Academy')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.College')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('password', models.CharField(default='000000', max_length=50)),
                ('name', models.CharField(max_length=40)),
                ('classes', models.CharField(max_length=40)),
                ('academy', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='account.Academy')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.College')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('belief', models.TextField(blank=True, null=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Academy')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.College')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.College'),
        ),
        migrations.AddField(
            model_name='activity',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Classroom'),
        ),
        migrations.AddField(
            model_name='activity',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Choice'),
        ),
        migrations.AddField(
            model_name='academy',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.College'),
        ),
    ]
