# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180402_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='switch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.Choice'),
        ),
    ]
